### ISSUE TITLE
Improve deduplication logic

### ISSUE THREAD

**Issue by ismailsimsek** [memiiso/debezium-server-iceberg#126]
according to this issue [DBZ-5591 ](https://issues.redhat.com/browse/DBZ-5591)

- deduplication should de prioritize (drop) snapshot events(`r`) against CDC)streaming events regardless of their `source__ts` value 

https://github.com/memiiso/debezium-server-iceberg/blob/63e17938492bb3c591a228f173fc9ef38f1e93e7/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/tableoperator/IcebergTableOperator.java#L94-L107

**Comment by maximethebault** [comment]
Couldn't the deduplication logic be simplified by only retaining records with the largest Kafka offset?

**Comment by ismailsimsek** [comment]
@maximethebault  with this consumer since there is no kafka in between it uses source source__ts field for ordering the events. 

actually this issue is fixed on debezium side by https://github.com/debezium/debezium/pull/3855
