### ISSUE TITLE
Blog post

### ISSUE THREAD

**Issue by gunnarmorling** [memiiso/debezium-server-iceberg#13]
Hey there, Gunnar here from the Debezium team. Just came across this project, this looks really cool! I was wondering whether you got any plans for blogging about this project? Perhaps a guest post on the debezium.io blog might be interesting to you? If so, let me know and we can talk about the details. Thanks a lot for your consideration and you effort working on this!

**Comment by ismailsimsek** [comment]
Hi @gunnarmorling its good idea, i can prepare something
