### ISSUE TITLE
Does this support with AWS Glue catalog for metadata?

### ISSUE THREAD

**Issue by kalyanjanaki777** [memiiso/debezium-server-iceberg#165]
I want to use this connector to write data to s3 and query using Amazon Athena. But there is dependency of AWS glue to be used as metadata. So how can we do that?

**Comment by ismailsimsek** [comment]
@kalyanjanaki777 AWS dependencies and iceberg glue catalog is packaged into the release. its possible to use with Glue Catalog as is. please post here if you run into any issue

**Comment by ismailsimsek** [comment]
Related #166
