### ISSUE TITLE
Iceberg Metadata Catalog Config

### ISSUE THREAD

**Issue by fritzwijaya** [memiiso/debezium-server-iceberg#166]
How to set the catalog implementation? Is there any docs for reference to set the config for supported metadata catalog?

**Comment by ismailsimsek** [comment]
@fritzwijaya its explained in the [last config line ](https://github.com/memiiso/debezium-server-iceberg/blob/master/docs/DOCS.md#configuration-properties)

and [example config is here](https://github.com/memiiso/debezium-server-iceberg/blob/064f9706da830d5bd464a24f5c6ffb7fdc09dd5e/debezium-server-iceberg-dist/src/main/resources/distro/conf/application.properties.example#L12-L17)

**Comment by fritzwijaya** [comment]
Thanks. Would take a look at it.

**Comment by fritzwijaya** [comment]
@ismailsimsek does it support to use Glue metadata catalog?

**Comment by ismailsimsek** [comment]
@fritzwijaya yes it supports it you just need to configure the catalog with your deployment. please feel free to post it here if you get any issue.

**Comment by fritzwijaya** [comment]
@ismailsimsek could you please share the sample config for set catalog impl?

**Comment by ismailsimsek** [comment]
glue catalog config should look like something below. additionally please make sure you have [all the libraries ](https://iceberg.apache.org/docs/latest/aws/#enabling-aws-integration) and necessary access to glue 

```
debezium.sink.iceberg.catalog-name=my_catalog
debezium.sink.iceberg.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog
debezium.sink.iceberg.warehouse=s3a://my-bucket/iceberg_warehouse
debezium.sink.iceberg.io-impl=org.apache.iceberg.aws.s3.S3FileIO
```
