### ISSUE TITLE
[Improvement] Use Append Iceberg Commit for Append Mode

### ISSUE THREAD

**Issue by wobu** [memiiso/debezium-server-iceberg#187]
When using the append mode in the debezium server iceberg project still Overwrite Commits are produced in the Iceberg table even if Append Commits would also technical work.

Append Commits / Snapshots in the Iceberg Table are have some benefits:
- easier error recovery on concurrency conflicts (like in a table maintenance scenario, see: https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/AppendFiles.java#L30)
- The Iceberg Table containing only append commits could be used as a source for streaming scenarios (see: https://iceberg.apache.org/docs/latest/flink/#streaming-read-1)

This should be easy fixable:

Enhance the code at https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/tableoperator/IcebergTableOperator.java#L182
with this check https://github.com/apache/iceberg/blob/master/flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java#L349

**Comment by ismailsimsek** [comment]
@wobu good point. adding if else with `files.deleteFiles().length > 0` should be enough right?

do you want to contribute it?

**Comment by wobu** [comment]
@ismailsimsek shoud be sufficient with my understanding

we will contribute, if we decide to focus on using this project. Currently the decision hasn't been made. Until then anyone is allowed to contribute :)
