### ISSUE TITLE
Target tables without table-prefix

### ISSUE THREAD

**Issue by sripathij** [memiiso/debezium-server-iceberg#211]
I am unable to use debezium.sink.iceberg.destination-regexp and debezium.sink.iceberg.destination-regexp-replace to create tables with the same name as in the source. Looks like that does not replace the table-prefix. It's almost like the table-prefix gets added after the regexp-replace is applied.

**Comment by ismailsimsek** [comment]
@sripathij correct it only applies to source `schema.tablename` 

https://github.com/memiiso/debezium-server-iceberg/blob/f28ce7eac438c2dde6c842fdf1994557d6749baa/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/IcebergChangeConsumer.java#L211-L216

**Comment by ismailsimsek** [comment]
@sripathij `table-prefix` is optional configuration you should be able to ommit it, that case it wont be added to target table name

**Comment by ismailsimsek** [comment]
Related to https://github.com/quarkusio/quarkus/issues/5947

opened PR for fix
