### ISSUE TITLE
case "double"missing from IcebergchangeEvent.java

### ISSUE THREAD

**Issue by Rishav-Git** [memiiso/debezium-server-iceberg#217]
case "double" is missing in the master branch on file: IcebergChangeEvent.scala.

Use Case:
When using debezium with MySQL database connector, it converts decimal type values to byte type by default. 
When the property: _decimal.handling.mode_ is set to double, the value should get converted to double type but the type gets converted to string since default case is string. 
Follow this link for more details:
 _https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-property-decimal-handling-mode:~:text=time%20zone%20information.-,Decimal%20types,-Debezium%20connectors%20handle_

We need to add case double to the existing code to fix _decimal.handling.mode_ property.

I have already used this code and tested it, working good for me. 

Example:

```
private static Type.PrimitiveType icebergFieldType(String fieldName, String fieldType) {
    switch (fieldType) {
      case "int8":
      case "int16":
      case "int32": // int 4 bytes
        return Types.IntegerType.get();
      case "int64": // long 8 bytes
        if (TS_MS_FIELDS.contains(fieldName)) {
          return Types.TimestampType.withZone();
        } else {
          return Types.LongType.get();
        }
      case "float8":
      case "float16":
      case "float32": // float is represented in 32 bits,
        return Types.FloatType.get();
      case "double":
      case "float64": // double is represented in 64 bits
        return Types.DoubleType.get();
      case "boolean":
        return Types.BooleanType.get();
      case "string":
        return Types.StringType.get();
      case "uuid":
        return Types.UUIDType.get();
      case "bytes":
        return Types.BinaryType.get();
      default:
        // default to String type
        return Types.StringType.get();
      //throw new RuntimeException("'" + fieldName + "' has "+fieldType+" type, "+fieldType+" not supported!");
    }
  }
```

**Comment by ismailsimsek** [comment]
Hi @Rishav-Git definitely can be added, please feel free to open PR. Thank you for reporting it

**Comment by Rishav-Git** [comment]
PR: #218

**Comment by Rishav-Git** [comment]
PR merged to master
