### ISSUE TITLE
Release latest master branch

### ISSUE THREAD

**Issue by Rishav-Git** [memiiso/debezium-server-iceberg#219]
Can we release the latest master branch? 
We can have the zip file ready in repo which can be readily accessed.
Last release I can see is last year.

**Comment by Rishav-Git** [comment]
@ismailsimsek

**Comment by ismailsimsek** [comment]
Something went wrong with latest release, I will check it soon..

**Comment by ismailsimsek** [comment]
manually fixed. seems like something is wrong with release actions. release is always created as draft

**Comment by Rishav-Git** [comment]
Thanks a lot! @ismailsimsek 
This will help me a lot as I will be actively using this project.

**Comment by ismailsimsek** [comment]
great to hear, please feel free to send pull requests or new requests. i will try to check the release issue soon, so we get master branch released correctly
