### ISSUE TITLE
Document Getting Started

### ISSUE THREAD

**Issue by ismailsimsek** [memiiso/debezium-server-iceberg#27]
add Getting Started section 
explain: 
- how to fork and open project with inteliJ. document shared run configs.
- how to build distribution. write mvn command.

**Comment by chulucninh09** [comment]
Hi, based on Docker file, I believe we can write a little about build instruction and dependencies like:
`openjdk11` + `maven`
and build command is `mvn clean package -Passembly -Dmaven.test.skip`

**Comment by ismailsimsek** [comment]
agree a page with basics should be enough. i haven't got time to write something any PR is welcome.

**Comment by chulucninh09** [comment]
Hi, I made this PR to enhance the documentation:
https://github.com/memiiso/debezium-server-iceberg/pull/61
