### ISSUE TITLE
specific character ($) in application.properties file

### ISSUE THREAD

**Issue by S-and-A** [memiiso/debezium-server-iceberg#304]
I am trying to get changes from the Oracle DB source. 

But I faced issue. The schema name is specified in the application.properties file. But didn't work correctly.

WARN  [io.deb.rel.RelationalDatabaseSchema] (debezium-oracleconnector-changes-change-event-source-coordinator) After applying the include/exclude list filters, no changes will be captured. Please check your configuration

application.properties
debezium.source.database.hostname=x.x.x.x
debezium.source.database.port=1521
debezium.source.database.user=user
debezium.source.database.password=pass
debezium.source.database.dbname=dbname
debezium.source.table.include.list=tst$db.table1
debezium.source.schema.include.list=tst$db

I already tried  tst\\$db ,  tst\$db , "tst\\$db", "tst\$db" , "tst$db" Not working. 
How to resolve it

**Comment by S-and-A** [comment]
@ismailsimsek

**Comment by ismailsimsek** [comment]
@S-and-A  Could you try with "tst*db" 
Also you can post it to  debezium community channel https://debezium.zulipchat.com
