### ISSUE TITLE
incorrect URI in example when hive is used

### ISSUE THREAD

**Issue by pandabrowski** [memiiso/debezium-server-iceberg#307]
there is a problem, when the hive metastore is used, the network name is used to create a host name.
Because network name includes '_', generated URI is incorrect.
to solve it you can change a name of network in dockerfile:
`networks:
  iceberg_net:
    name: "icebergnet"`

**Comment by ismailsimsek** [comment]
Thank you @pandabrowski, do you like to send PR for fix?

**Comment by pandabrowski** [comment]
sorry, i'm short on time.
