### ISSUE TITLE
Unable to compile as per instruction

### ISSUE THREAD

**Issue by kowshikdutta** [memiiso/debezium-server-iceberg#333]
While running the command, "mvn -Passembly -Dmaven.test.skip package"...getting the below error:

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.658 s
[INFO] Finished at: 2024-05-30T10:42:20Z
[INFO] Final Memory: 99M/340M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.10.0:build (default) on project debezium-server-iceberg-sink: Execution default of goal io.quarkus:quarkus-maven-plugin:3.10.0:build failed: Unable to load the mojo 'build' (or one of its required components) from the plugin 'io.quarkus:quarkus-maven-plugin:3.10.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider was bound.
[ERROR]   while locating io.quarkus.maven.BuildMojo
[ERROR]   at ClassRealm[plugin>io.quarkus:quarkus-maven-plugin:3.10.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR]   while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=io.quarkus:quarkus-maven-plugin:3.10.0:build)
[ERROR] 
[ERROR] 1 error
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: io.quarkus:quarkus-maven-plugin:3.10.0:build
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :debezium-server-iceberg-sink

**Comment by ismailsimsek** [comment]
@kowshikdutta what is the maven version? 

could you try it with higher maven version, with 3.9.6 or above ?

**Comment by kowshikdutta** [comment]
Thanks a lot..I upgraded maven to 3.9.7 and the build completed successfully...
