### ISSUE TITLE
Debezium version  Debezium 3.0.0.Final 

### ISSUE THREAD

**Issue by GOVINDARAMTEKKAR97** [memiiso/debezium-server-iceberg#429]
Hi @ismailsimsek,

 Hope you are doing well. I saw Debezium community release the version 3.0.0.  While using  Debezium 2.7 version it is  having depreciated parameter and we can't used the feature according to requirement.
 
Can you please update the code for Debezium version 3 (https://debezium.io/blog/2024/10/02/debezium-3-0-final-released/#oracle-changes), It will help a lot. Please let me know your response on that. 

   Thank you for understanding.

Regards,
Govinda

**Comment by ismailsimsek** [comment]
With this upgrade : related to #447
we should also keep Quarkus version in sync with Debezium because you might find other incompatibilities.
or remove it and let the parent Debezium project to define quarkus version
