### ISSUE TITLE
[Feature Request] Full Schema Evolution

### ISSUE THREAD

**Issue by ayush-san** [memiiso/debezium-server-iceberg#49]
Are there any plans to support schema evolution in this project? 

Things to consider 
- Should be column order agnostic(AFAIK till iceberg 0.11, columns were referred by the column id so the column order mattered a lot while using iceberg flink sink)
- Typecasting consideration(int to string is a valid schema evolution but the downstream jobs/queries will start to fail)

**Comment by ismailsimsek** [comment]
Hi @ayush-san i believe both features are currently sported, you could see it in this [unit test class](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/test/java/io/debezium/server/iceberg/IcebergChangeConsumerTest.java#L63)

current behavior:
- source filed order is ignored. fields are mapped to iceberg field order using field name.
- typecasting is allowed and done by Jackson. source value converted to iceberg type.

current issue with typecasting is Jackson type casting returns default values when types are not compatible. Ideally it should throw error when casting incompatible types/values. you could see it in [this test](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/test/java/io/debezium/server/iceberg/IcebergChangeConsumerTest.java#L200)
convert integer -> string  OK 
convert string -> integer  Fail (current behaviors will return `0` without error)

Im planing to document current schema evolution behavior. then look into improvements.

**Comment by ayush-san** [comment]
@ismailsimsek Yes but here we are manually updating the schema, I was thinking that we can refer to the schema registry if we use Avro type and use that for evolving schema in the runtime

> fields are mapped to iceberg field order using field name.
Can you please point me to the code where this is happening

**Comment by ismailsimsek** [comment]
i see. current implementation is supporting only json events, json events are crying schema with event and not requiring schema registry.

current logic is in [this class ](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/IcebergUtil.java#L103)
this method is doing data[ type conversion ](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/IcebergUtil.java#L124)

[here](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/main/java/io/debezium/server/iceberg/IcebergUtil.java#L190) for the first run, we take event schema and use it to create iceberg schema

**Comment by ismailsimsek** [comment]
implemented by https://github.com/memiiso/debezium-server-iceberg/issues/68
