### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by racevedoo** [memiiso/debezium-server-iceberg#52]
Hi all,

I was trying to run the project locally and I managed to do it, but I thought it would be nice to provide a docker image (possibly reading `application.properties` from a specific file instead of classpath).

Are there any plans to do this? I can contribute if necessary

**Comment by ismailsimsek** [comment]
+1 i think its good idea to add Docker image. Im not working on it please feel free to send PR

**Comment by racevedoo** [comment]
I'll start working on this
