### ISSUE TITLE
Support Spark streaming

### ISSUE THREAD

**Issue by melin** [memiiso/debezium-server-iceberg#77]
Use Spark Streaming to consume Debezium embedded data and use Spark to write Iceberg or Hudi. Is it easier?

**Comment by ismailsimsek** [comment]
@melin that should easily be possible. [debezium-server-batch](https://github.com/memiiso/debezium-server-batch) project has `sparkbatch`, `sparkbigquerybatch` and and `bigquerybatch`(native) consumers implemented.  Similar to sparkbigquery with minor changes it should be possible to create sparkhudi or sparkiceberg consumers.  please feel free to open feature request or pull request.

spark consumer is not using streaming though, probably that will be good feature to add
