### ISSUE TITLE
Any example of tool or program that read data that genereated from ice berg

### ISSUE THREAD

**Issue by deaw0003** [memiiso/debezium-server-iceberg#96]
Any example of tool or program that read table/data in s3 bucket that genereated from iceberg in upsert mode ?

**Comment by ismailsimsek** [comment]
@deaw0003  This is spark example[ reading s3(minio) data ](https://github.com/memiiso/debezium-server-iceberg/blob/master/debezium-server-iceberg-sink/src/test/java/io/debezium/server/iceberg/testresources/BaseSparkTest.java) . its used for integration test. [Here](https://iceberg.apache.org/docs/latest/getting-started/) you can see more details how to use spark to read iceberg table.

If you are working with S3 i recommend [configuring iceberg-consumer](https://github.com/memiiso/debezium-server-iceberg/blob/master/docs/DOCS.md#configuration-properties) to use [Glue Catalog](https://iceberg.apache.org/docs/latest/aws/#glue-catalog).  With Glue Catalog you can read the data using Spark, AWS Glue Job or AWS Athena.

**Comment by deaw0003** [comment]
Thank you very much.
